import { Award, Medal, Gem } from 'lucide-react';
import React from 'react';

export default function SubscriptionSection() {
  return (
    <>
    <section id="packages" className="py-16 md:py-20 px-4 md:px-6 w-full bg-white dark:bg-gray-900 transition-colors duration-300" style={{fontFamily: 'Pier Sans, sans-serif'}}>
        <div className="container mx-auto max-w-7xl">
            <div className="text-center mb-10 md:mb-12">
                <h2 className="text-3xl md:text-4xl font-medium mb-4 text-gray-900 dark:text-white transition-colors duration-300" style={{fontFamily: 'Pier Sans, sans-serif'}}>Choose Your <span className="text-green-500 dark:text-green-400">Trading Edge</span></h2>
                <p className="text-lg md:text-xl text-[#19235d] dark:text-gray-300 max-w-3xl mx-auto mb-2 transition-colors duration-300">
                    Join 150+ successful traders using our proven system
                </p>
                <div className="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-700 rounded-lg p-3 max-w-2xl mx-auto mt-4 transition-colors duration-300">
                    <p className="text-green-800 dark:text-green-300 text-sm font-medium transition-colors duration-300">
                        ✅ Established system with proven track record - $230k+ profit generated by our active users
                    </p>
                </div>
                <div className="flex flex-wrap justify-center items-center space-x-2 md:space-x-6 mt-4">
                    <div className="flex items-center mb-2 md:mb-0">
                        <i className="fas fa-star text-green-500 dark:text-green-400 mr-1"></i>
                        <i className="fas fa-star text-green-500 dark:text-green-400 mr-1"></i>
                        <i className="fas fa-star text-green-500 dark:text-green-400 mr-1"></i>
                        <i className="fas fa-star text-green-500 dark:text-green-400 mr-1"></i>
                        <i className="fas fa-star text-green-500 dark:text-green-400 mr-2"></i>
                        <span className="text-[#19235d] dark:text-gray-300 font-medium transition-colors duration-300"></span>
                    </div>
                    <div className="h-6 border-l border-gray-300 dark:border-gray-600 hidden md:block transition-colors duration-300"></div>
                    <div className="flex items-center">
                        <i className="fas fa-shield-alt text-green-500 dark:text-green-400 mr-2"></i>
                        <span className="text-[#19235d] dark:text-gray-300 font-medium transition-colors duration-300">Secure Payment</span>
                    </div>
                </div>
            </div>

            {/* Card Container with Shadow Effect */}
            <div className="relative z-0 mb-12 shadow-lg rounded-full">
                
                {/* Pricing Cards */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-0 relative z-10">
                    {/* Silver Package */}
                    <div className="pricing-card bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 md:rounded-l-2xl p-6 md:p-8 transition-all duration-300 hover:shadow-xl dark:hover:shadow-gray-900/50 hover:z-10 relative flex flex-col h-full">
                        <div className="absolute top-0 right-0 left-0 h-1 bg-gradient-to-r from-green-300 to-gray-300 dark:from-green-400 dark:to-gray-500"></div>
                        <div className="text-center mb-6">
                            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gray-100 dark:bg-gray-700 mb-4">
                                <Award className="w-8 h-8 text-gray-600 dark:text-gray-300" />
                            </div>
                            <h3 className="text-2xl font-medium text-gray-900 dark:text-white">Silver</h3>
                            <div className="text-gray-500 dark:text-gray-400 mt-1">Perfect for beginners</div>
                            <div className="text-sm bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-full px-3 py-1 inline-block mt-2">For Single Direction Trading</div>
                        </div>
                        
                        <div className="text-center mb-6 pb-6 border-b border-gray-100 dark:border-gray-700">
                            <div className="bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-xs font-medium px-3 py-1 rounded-full inline-block mb-3">
                                Standard Pricing
                            </div>
                            <div className="flex items-end justify-center mt-2">
                                <span className="text-4xl md:text-5xl font-medium text-gray-900 dark:text-white">$ 1,099</span>
                                <span className="text-gray-500 dark:text-gray-400 ml-2 mb-1">/lifetime</span>
                            </div>
                            <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">One-time payment, no recurring fees</p>
                        </div>
                        
                        <div className="mb-6 md:mb-8 flex-grow">
                            <h4 className="font-medium mb-3 text-center text-gray-900 dark:text-white">Key Features:</h4>
                            <ul className="space-y-3">
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Trading Direction:</strong> Choose Buy Only OR Sell Only</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Instruments:</strong> EURUSD, GOLD</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Stop-Loss:</strong> Standard unified protection</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Interface:</strong> Basic dashboard</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-times-circle text-red-400 dark:text-red-500 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-400 dark:text-gray-500">Bi-directional trading</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-times-circle text-red-400 dark:text-red-500 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-400 dark:text-gray-500">Enhanced re-entry logic</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-times-circle text-red-400 dark:text-red-500 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-400 dark:text-gray-500">Advanced customization</span>
                                </li>
                            </ul>
                        </div>
                        
                        <div className="mt-auto">
                            <a href="https://buy.stripe.com/6oUaEXc2Lg8j6OP94e57W07" data-price="1099" data-package="silver" target="_blank" rel="noreferrer" className="block w-full py-4 border-2 border-gray-600 dark:border-gray-500 text-gray-800 dark:text-gray-200 font-medium rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors duration-300 flex items-center justify-center">
                                Choose Silver <i className="fas fa-arrow-right ml-2"></i>
                            </a>
                            <p className="text-center text-sm text-gray-500 dark:text-gray-400 mt-4">30-day email support included</p>
                        </div>
                    </div>
                    
                    {/* Gold Package */}
                    <div className="pricing-card bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 p-6 md:p-8 transition-all duration-300 hover:shadow-xl dark:hover:shadow-gray-900/50 hover:z-10 relative flex flex-col h-full">
                        <div className="absolute top-0 right-0 left-0 h-1 bg-gradient-to-r from-gray-200 to-gray-300 dark:from-gray-400 dark:to-gray-500"></div>
                        <div className="text-center mb-6 pt-4">
                            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gray-100 dark:bg-gray-700 mb-4">
                                <Medal className="w-8 h-8 text-yellow-600 dark:text-yellow-400" />
                            </div>
                            <h3 className="text-2xl font-medium text-gray-900 dark:text-white">Gold</h3>
                            <div className="text-gray-500 dark:text-gray-400 mt-1">For professional traders</div>
                            <div className="text-sm bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded-full px-3 py-1 inline-block mt-2">Best for Bi-directional Trading</div>
                        </div>
                        
                        <div className="text-center mb-6 pb-6 border-b border-gray-100 dark:border-gray-700">
                            <div className="bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-xs font-medium px-3 py-1 rounded-full inline-block mb-3">
                                Standard Pricing
                            </div>
                            <div className="flex items-end justify-center mt-2">
                                <span className="text-4xl md:text-5xl font-medium text-gray-900 dark:text-white">$ 1,399</span>
                                <span className="text-gray-500 dark:text-gray-400 ml-2 mb-1">/lifetime</span>
                            </div>
                            <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">One-time payment, no recurring fees</p>
                        </div>
                        
                        <div className="mb-6 md:mb-8 flex-grow">
                            <h4 className="font-medium mb-3 text-center text-gray-900 dark:text-white">Everything in Silver, Plus:</h4>
                            <ul className="space-y-3">
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Trading Direction:</strong> Buy Only, Sell Only and Both Mode</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Profit Potential:</strong> Increases with bi-directional trading</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Instruments:</strong> EURUSD, GOLD, GBPUSD, AUDUSD, USDJPY</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Market Adaptability:</strong> Profit in trending markets</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Risk Management:</strong> Advanced protection</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-times-circle text-red-400 dark:text-red-500 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-400 dark:text-gray-500">Custom trading schedules</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-times-circle text-red-400 dark:text-red-500 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-400 dark:text-gray-500">Advanced customization options</span>
                                </li>
                            </ul>
                        </div>
                        
                        <div className="mt-auto">
                            <a href="https://buy.stripe.com/aFa28rfeXaNZ6OP1BM57W08" data-price="1399" data-package="gold" target="_blank" rel="noreferrer" className="block w-full py-4 border-2 border-gray-600 dark:border-gray-500 text-gray-800 dark:text-gray-200 font-medium rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors duration-300 flex items-center justify-center">
                                Choose Gold <i className="fas fa-arrow-right ml-2"></i>
                            </a>
                            <p className="text-center text-sm text-gray-500 dark:text-gray-400 mt-4">90-day priority support</p>
                        </div>
                    </div>
                    
                    {/* Diamond Package */}
                    <div className="pricing-card diamond-package bg-white dark:bg-gray-800 border-2 border-green-400 dark:border-green-500 md:rounded-r-2xl p-6 md:p-8 md:transform md:scale-105 shadow-xl dark:shadow-gray-900/50 z-20 transition-all duration-300 hover:shadow-2xl dark:hover:shadow-gray-900/70 relative flex flex-col h-full">
                        <div className="absolute -top-8 inset-x-0 flex justify-center z-30">
                            <span className="bg-green-500 dark:bg-green-600 text-white font-medium px-6 py-2 rounded-full text-sm uppercase tracking-wide shadow-md">Most Popular</span>
                            </div>
                        {/* Best Seller Tag */}
                        <div className="absolute -right-2 top-12 bg-red-500 dark:bg-red-600 text-white px-4 py-1 rounded-l-lg shadow-md transform rotate-0 z-30 hidden md:block">
                            <span className="text-sm font-medium">BEST SELLER</span>
                            <div className="absolute top-full right-0 w-2 h-2 bg-red-700 dark:bg-red-800" style={{clipPath: "polygon(100% 0, 0 0, 100% 100%)"}}></div>
                        </div>
                        <div className="absolute top-0 right-0 left-0 h-1 bg-gradient-to-r from-green-400 to-green-600 dark:from-green-500 dark:to-green-700"></div>
                        <div className="text-center mb-6 pt-4">
                            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-blue-100 dark:bg-blue-900/30 mb-4">
                                <Gem className="w-8 h-8 text-blue-600 dark:text-blue-400" />
                            </div>
                            <h3 className="text-2xl font-medium text-gray-900 dark:text-white">Diamond</h3>
                            <div className="text-gray-500 dark:text-gray-400 mt-1">For professional traders</div>
                            <div className="text-sm bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded-full px-3 py-1 inline-block mt-2">Maximum Customization & Power</div>
                        </div>
                        
                        <div className="text-center mb-6 pb-6 border-b border-gray-100 dark:border-gray-700">
                            <div className="bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-xs font-medium px-3 py-1 rounded-full inline-block mb-3">
                                Standard Pricing
                            </div>
                            <div className="flex items-end justify-center mt-2">
                                <span className="text-4xl md:text-5xl font-medium text-gray-900 dark:text-white">$ 1,999</span>
                                <span className="text-gray-500 dark:text-gray-400 ml-2 mb-1">/lifetime</span>
                            </div>
                            <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">One-time payment, no recurring fees</p>
                        </div>
                        
                        <div className="mb-6 md:mb-8 flex-grow">
                            <h4 className="font-medium mb-3 text-center text-gray-900 dark:text-white">Everything in Gold, Plus:</h4>
                            <ul className="space-y-3">
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Advanced Features:</strong> Full system customization</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Trading Schedule:</strong> Set custom trading hours</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Price Range:</strong> Set specific trading zones</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Position Sizing:</strong> Advanced risk control</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-green-500 dark:text-green-400"><strong>Instruments:</strong> Unlimited Pairs</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Re-entry:</strong> Visual tracking lines</span>
                                </li>
                                <li className="flex items-start">
                                    <i className="fas fa-check-circle text-green-500 dark:text-green-400 mr-2 text-lg mt-0.5"></i>
                                    <span className="text-gray-700 dark:text-gray-300"><strong>Support:</strong> Lifetime VIP Support</span>
                                </li>
                            </ul>
                        </div>
                        
                        <div className="mt-auto">
                            <a href="https://buy.stripe.com/14AeVd4Aj09l0qr6W657W09" data-price="1999" data-package="diamond" target="_blank" rel="noreferrer" className="block w-full py-4 bg-blue-500 dark:bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-600 dark:hover:bg-blue-700 transition-colors duration-300 flex items-center justify-center shadow-md">
                                Choose Diamond <i className="fas fa-arrow-right ml-2"></i>
                            </a>
                            <p className="text-center text-sm text-gray-500 dark:text-gray-400 mt-4">Lifetime VIP support</p>
                        </div>
                    </div>
                </div>
            </div>
            
           

            {/* Premium What Happens Next Section */}
            <div className="max-w-6xl mx-auto mb-16">
                <div className="relative">
                    {/* Background Elements */}
                    <div className="absolute inset-0 bg-gradient-to-br from-blue-50/50 via-transparent to-emerald-50/50 dark:from-blue-900/20 dark:via-transparent dark:to-emerald-900/20 rounded-3xl transition-colors duration-300"></div>
                    <div className="absolute top-0 left-1/2 transform -translate-x-1/2 w-32 h-1 bg-gradient-to-r from-blue-500 to-emerald-500 dark:from-blue-400 dark:to-emerald-400 rounded-full transition-colors duration-300"></div>
                    
                    <div className="relative bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border border-gray-100/50 dark:border-gray-700/50 rounded-3xl p-8 md:p-12 shadow-xl dark:shadow-gray-900/50 transition-colors duration-300">
                        {/* Header */}
                        <div className="text-center mb-12">
                            <div className="inline-flex items-center space-x-2 bg-blue-500/10 dark:bg-blue-500/20 border border-blue-500/20 dark:border-blue-500/30 rounded-full px-6 py-2 text-blue-600 dark:text-blue-400 text-sm font-medium mb-6 transition-colors duration-300">
                                <i className="fas fa-clipboard-check w-4 h-4"></i>
                                <span>NEXT STEPS</span>
                            </div>
                            <h3 className="text-3xl md:text-4xl font-medium text-gray-900 dark:text-white mb-4 font-poppins transition-colors duration-300">
                                <span className="bg-gradient-to-r from-blue-600 to-emerald-600 dark:from-blue-400 dark:to-emerald-400 bg-clip-text text-transparent">
                                    What Happens Next?
                                </span>
                            </h3>
                            <p className="text-gray-600 dark:text-gray-300 text-lg max-w-2xl mx-auto transition-colors duration-300">
                                Your journey to profitable trading starts immediately after purchase
                            </p>
                        </div>
                        
                        {/* Process Steps */}
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                            {/* Step 1 */}
                            <div className="group relative">
                                <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/10 to-green-500/10 dark:from-emerald-500/20 dark:to-green-500/20 rounded-2xl transform group-hover:scale-105 transition-all duration-300"></div>
                                <div className="relative bg-white/60 dark:bg-gray-800/60 backdrop-blur-sm rounded-2xl p-6 border border-emerald-100/50 dark:border-emerald-500/20 shadow-lg dark:shadow-gray-900/50 group-hover:shadow-xl dark:group-hover:shadow-gray-900/70 transition-all duration-300 text-center">
                                    <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-emerald-500 to-green-600 dark:from-emerald-400 dark:to-green-500 rounded-2xl mb-6 shadow-lg">
                                        <span className="text-2xl font-medium text-white">1</span>
                                    </div>
                                    <h4 className="text-lg font-medium text-gray-900 dark:text-white mb-3 font-poppins transition-colors duration-300">Instant Access</h4>
                                    <p className="text-gray-600 dark:text-gray-300 text-sm leading-relaxed transition-colors duration-300">You&apos;ll receive login details to download your system immediately</p>
                                </div>
                            </div>
                            
                            {/* Step 2 */}
                            <div className="group relative">
                                <div className="absolute inset-0 bg-gradient-to-br from-blue-500/10 to-cyan-500/10 dark:from-blue-500/20 dark:to-cyan-500/20 rounded-2xl transform group-hover:scale-105 transition-all duration-300"></div>
                                <div className="relative bg-white/60 dark:bg-gray-800/60 backdrop-blur-sm rounded-2xl p-6 border border-blue-100/50 dark:border-blue-500/20 shadow-lg dark:shadow-gray-900/50 group-hover:shadow-xl dark:group-hover:shadow-gray-900/70 transition-all duration-300 text-center">
                                    <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-blue-500 to-cyan-600 dark:from-blue-400 dark:to-cyan-500 rounded-2xl mb-6 shadow-lg">
                                        <span className="text-2xl font-medium text-white">2</span>
                                    </div>
                                    <h4 className="text-lg font-medium text-gray-900 dark:text-white mb-3 font-poppins transition-colors duration-300">Telegram Support</h4>
                                    <p className="text-gray-600 dark:text-gray-300 text-sm leading-relaxed transition-colors duration-300">I&apos;ll personally add you to our private community group</p>
                        </div>
                            </div>
                            
                            {/* Step 3 */}
                            <div className="group relative">
                                <div className="absolute inset-0 bg-gradient-to-br from-purple-500/10 to-pink-500/10 dark:from-purple-500/20 dark:to-pink-500/20 rounded-2xl transform group-hover:scale-105 transition-all duration-300"></div>
                                <div className="relative bg-white/60 dark:bg-gray-800/60 backdrop-blur-sm rounded-2xl p-6 border border-purple-100/50 dark:border-purple-500/20 shadow-lg dark:shadow-gray-900/50 group-hover:shadow-xl dark:group-hover:shadow-gray-900/70 transition-all duration-300 text-center">
                                    <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-purple-500 to-pink-600 dark:from-purple-400 dark:to-pink-500 rounded-2xl mb-6 shadow-lg">
                                        <span className="text-2xl font-medium text-white">3</span>
                                    </div>
                                    <h4 className="text-lg font-medium text-gray-900 dark:text-white mb-3 font-poppins transition-colors duration-300">Setup Assistance</h4>
                                    <p className="text-gray-600 dark:text-gray-300 text-sm leading-relaxed transition-colors duration-300">Follow our step-by-step installation guide or get personal help</p>
                        </div>
                    </div>
                    
                            {/* Step 4 */}
                            <div className="group relative">
                                <div className="absolute inset-0 bg-gradient-to-br from-orange-500/10 to-red-500/10 dark:from-orange-500/20 dark:to-red-500/20 rounded-2xl transform group-hover:scale-105 transition-all duration-300"></div>
                                <div className="relative bg-white/60 dark:bg-gray-800/60 backdrop-blur-sm rounded-2xl p-6 border border-orange-100/50 dark:border-orange-500/20 shadow-lg dark:shadow-gray-900/50 group-hover:shadow-xl dark:group-hover:shadow-gray-900/70 transition-all duration-300 text-center">
                                    <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-orange-500 to-red-600 dark:from-orange-400 dark:to-red-500 rounded-2xl mb-6 shadow-lg">
                                        <span className="text-2xl font-medium text-white">4</span>
                                    </div>
                                    <h4 className="text-lg font-medium text-gray-900 dark:text-white mb-3 font-poppins transition-colors duration-300">Start Trading</h4>
                                    <p className="text-gray-600 dark:text-gray-300 text-sm leading-relaxed transition-colors duration-300">Be up and running within 5 minutes on your preferred broker</p>
                    </div>
                </div>
            </div>

                        {/* Bottom CTA */}
                        <div className="mt-12 text-center">
                            <div className="inline-flex items-center space-x-2 bg-gradient-to-r from-emerald-500/10 to-blue-500/10 dark:from-emerald-500/20 dark:to-blue-500/20 border border-emerald-200/50 dark:border-emerald-500/30 rounded-full px-8 py-4 transition-colors duration-300">
                                <p className="text-sm text-gray-700 dark:text-gray-300 font-medium transition-colors duration-300">
                                    Ready to join our community of successful traders?
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            


            
            {/* Guarantee Section */}
           


    
    <section id="testimonials" className="py-16 md:py-20 px-4 md:px-6 bg-gradient-to-br from-gray-50 via-white to-gray-100 dark:bg-gradient-to-br dark:from-gray-900 dark:via-black dark:to-gray-900 w-full relative overflow-hidden">
        {/* Animated Background Elements */}
        <div className="absolute inset-0">
            {/* Floating Trading Charts */}
            <div className="absolute top-20 left-10 w-16 h-16 opacity-20 animate-float">
                <div className="w-full h-full bg-gradient-to-br from-emerald-500 to-green-600 rounded-lg transform rotate-12"></div>
            </div>
            <div className="absolute top-40 right-20 w-12 h-12 opacity-15 animate-float-delayed">
                <div className="w-full h-full bg-gradient-to-br from-blue-500 to-cyan-600 rounded-lg transform -rotate-12"></div>
            </div>
            <div className="absolute bottom-40 left-20 w-20 h-20 opacity-10 animate-float-slow">
                <div className="w-full h-full bg-gradient-to-br from-purple-500 to-pink-600 rounded-lg transform rotate-45"></div>
            </div>
            
        </div>

        <div className="container mx-auto max-w-7xl relative z-10">
            {/* Header */}
            <div className="text-center mb-16">
                <div className="inline-flex items-center space-x-2 bg-emerald-500/10 border border-emerald-500/20 rounded-full px-6 py-2 text-emerald-600 dark:text-emerald-400 text-sm font-medium mb-6">
                    <Award className="w-4 h-4" />
                    <span>PROVEN RESULTS</span>
                </div>
                
                <h2 className="text-3xl md:text-4xl font-medium text-gray-900 dark:text-white mb-6 font-poppins">
                    <span className="bg-gradient-to-r from-emerald-600 to-blue-600 dark:from-emerald-400 dark:to-blue-400 bg-clip-text text-transparent">
                        Proven Results from Our Community
                    </span>
                </h2>
                
                <p className="text-lg md:text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto leading-relaxed">
                    Real results from our 150+ founding members using our established system
                </p>
            </div>
            
            {/* Animated Trading Results Display */}
            <div className="max-w-6xl mx-auto">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    {/* Result Card 1 */}
                    <div className="group relative">
                        <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/20 to-green-500/20 rounded-3xl transform group-hover:scale-105 transition-all duration-500 animate-fade-in-up"></div>
                        <div className="relative bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm rounded-3xl p-8 border border-emerald-200/50 dark:border-emerald-700/50 shadow-xl group-hover:shadow-2xl transition-all duration-500">
                            {/* Animated Chart */}
                            <div className="mb-6">
                                <div className="h-32 bg-gradient-to-br from-emerald-50 to-green-50 dark:from-emerald-900/20 dark:to-green-900/20 rounded-2xl p-4 relative overflow-hidden">
                                    {/* Simulated Trading Chart */}
                                    <div className="absolute inset-4">
                                        <svg viewBox="0 0 200 100" className="w-full h-full">
                                            <polyline
                                                points="0,80 20,70 40,60 60,45 80,35 100,25 120,20 140,15 160,10 180,5 200,0"
                                                fill="none"
                                                stroke="url(#gradient1)"
                                                strokeWidth="3"
                                                className="animate-draw-line"
                                            />
                                            <defs>
                                                <linearGradient id="gradient1" x1="0%" y1="0%" x2="100%" y2="0%">
                                                    <stop offset="0%" stopColor="#10b981" />
                                                    <stop offset="100%" stopColor="#059669" />
                                                </linearGradient>
                                            </defs>
                                        </svg>
                                    </div>
                                </div>
                            </div>
                            
                            <div className="text-center">
                                <div className="text-3xl font-medium text-emerald-600 dark:text-emerald-400 mb-2 font-poppins">+$2,847</div>
                                <p className="text-gray-600 dark:text-gray-300 text-sm font-medium">EURUSD Trade</p>
                                <p className="text-gray-500 dark:text-gray-400 text-xs mt-1">Member: Alex K.</p>
                    </div>
                        </div>
                        </div>

                    {/* Result Card 2 */}
                    <div className="group relative">
                        <div className="absolute inset-0 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-3xl transform group-hover:scale-105 transition-all duration-500 animate-fade-in-up delay-200"></div>
                        <div className="relative bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm rounded-3xl p-8 border border-blue-200/50 dark:border-blue-700/50 shadow-xl group-hover:shadow-2xl transition-all duration-500">
                            {/* Animated Chart */}
                            <div className="mb-6">
                                <div className="h-32 bg-gradient-to-br from-blue-50 to-cyan-50 dark:from-blue-900/20 dark:to-cyan-900/20 rounded-2xl p-4 relative overflow-hidden">
                                    {/* Simulated Trading Chart */}
                                    <div className="absolute inset-4">
                                        <svg viewBox="0 0 200 100" className="w-full h-full">
                                            <polyline
                                                points="0,90 20,85 40,75 60,60 80,45 100,30 120,20 140,15 160,10 180,8 200,5"
                                                fill="none"
                                                stroke="url(#gradient2)"
                                                strokeWidth="3"
                                                className="animate-draw-line-delayed"
                                            />
                                            <defs>
                                                <linearGradient id="gradient2" x1="0%" y1="0%" x2="100%" y2="0%">
                                                    <stop offset="0%" stopColor="#3b82f6" />
                                                    <stop offset="100%" stopColor="#06b6d4" />
                                                </linearGradient>
                                            </defs>
                                        </svg>
                                    </div>
                                </div>
                            </div>
                            
                            <div className="text-center">
                                <div className="text-3xl font-medium text-blue-600 dark:text-blue-400 mb-2 font-poppins">+$4,231</div>
                                <p className="text-gray-600 dark:text-gray-300 text-sm font-medium">GOLD Trade</p>
                                <p className="text-gray-500 dark:text-gray-400 text-xs mt-1">Member: Sarah M.</p>
                    </div>
                </div>
                    </div>
                    
                    {/* Result Card 3 */}
                    <div className="group relative">
                        <div className="absolute inset-0 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-3xl transform group-hover:scale-105 transition-all duration-500 animate-fade-in-up delay-400"></div>
                        <div className="relative bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm rounded-3xl p-8 border border-purple-200/50 dark:border-purple-700/50 shadow-xl group-hover:shadow-2xl transition-all duration-500">
                            {/* Animated Chart */}
                            <div className="mb-6">
                                <div className="h-32 bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 rounded-2xl p-4 relative overflow-hidden">
                                    {/* Simulated Trading Chart */}
                                    <div className="absolute inset-4">
                                        <svg viewBox="0 0 200 100" className="w-full h-full">
                                            <polyline
                                                points="0,85 20,80 40,70 60,55 80,40 100,25 120,15 140,10 160,8 180,6 200,4"
                                                fill="none"
                                                stroke="url(#gradient3)"
                                                strokeWidth="3"
                                                className="animate-draw-line-slow"
                                            />
                                            <defs>
                                                <linearGradient id="gradient3" x1="0%" y1="0%" x2="100%" y2="0%">
                                                    <stop offset="0%" stopColor="#8b5cf6" />
                                                    <stop offset="100%" stopColor="#ec4899" />
                                                </linearGradient>
                                            </defs>
                                        </svg>
                                    </div>
                                </div>
                            </div>
                            
                            <div className="text-center">
                                <div className="text-3xl font-medium text-purple-600 dark:text-purple-400 mb-2 font-poppins">+$3,156</div>
                                <p className="text-gray-600 dark:text-gray-300 text-sm font-medium">GBPUSD Trade</p>
                                <p className="text-gray-500 dark:text-gray-400 text-xs mt-1">Member: David L.</p>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Animated Stats Bar */}
                <div className="mt-12 bg-white/60 dark:bg-gray-800/60 backdrop-blur-sm rounded-2xl p-8 border border-gray-200/50 dark:border-gray-700/50 shadow-lg">
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
                        <div className="group">
                            <div className="text-4xl font-medium text-emerald-600 dark:text-emerald-400 mb-2 font-poppins animate-count-up">150+</div>
                            <p className="text-gray-600 dark:text-gray-300 font-medium">Active Members</p>
                        </div>
                        <div className="group">
                            <div className="text-4xl font-medium text-blue-600 dark:text-blue-400 mb-2 font-poppins animate-count-up-delayed">$230k+</div>
                            <p className="text-gray-600 dark:text-gray-300 font-medium">Total Profits</p>
                        </div>
                        <div className="group">
                            <div className="text-4xl font-medium text-purple-600 dark:text-purple-400 mb-2 font-poppins animate-count-up-slow">6+ Months</div>
                            <p className="text-gray-600 dark:text-gray-300 font-medium">Proven Track Record</p>
                    </div>
                        </div>
                    </div>
                </div>
                
            {/* Disclaimer */}
            <div className="mt-12 text-center">
                <div className="inline-flex items-center space-x-2 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-full px-6 py-3">
                    <p className="text-sm text-gray-600 dark:text-gray-400 font-medium">
                        *These are real trading results from our clients. Trading involves substantial risk of loss and is not suitable for everyone. Past performance is not indicative of future results.
                    </p>
                </div>
            </div>
        </div>

        {/* Custom Animations */}
        <style dangerouslySetInnerHTML={{
            __html: `
                @keyframes float {
                    0%, 100% { transform: translateY(0px) rotate(0deg); }
                    50% { transform: translateY(-20px) rotate(5deg); }
                }
                @keyframes float-delayed {
                    0%, 100% { transform: translateY(0px) rotate(0deg); }
                    50% { transform: translateY(-15px) rotate(-3deg); }
                }
                @keyframes float-slow {
                    0%, 100% { transform: translateY(0px) rotate(0deg); }
                    50% { transform: translateY(-25px) rotate(8deg); }
                }
                @keyframes fade-in-up {
                    0% { opacity: 0; transform: translateY(30px); }
                    100% { opacity: 1; transform: translateY(0); }
                }
                @keyframes draw-line {
                    0% { stroke-dasharray: 0 1000; }
                    100% { stroke-dasharray: 1000 0; }
                }
                @keyframes draw-line-delayed {
                    0% { stroke-dasharray: 0 1000; }
                    100% { stroke-dasharray: 1000 0; }
                }
                @keyframes draw-line-slow {
                    0% { stroke-dasharray: 0 1000; }
                    100% { stroke-dasharray: 1000 0; }
                }
                @keyframes count-up {
                    0% { opacity: 0; transform: scale(0.5); }
                    100% { opacity: 1; transform: scale(1); }
                }
                .animate-float { animation: float 6s ease-in-out infinite; }
                .animate-float-delayed { animation: float-delayed 8s ease-in-out infinite; }
                .animate-float-slow { animation: float-slow 10s ease-in-out infinite; }
                .animate-fade-in-up { animation: fade-in-up 0.8s ease-out forwards; }
                .animate-draw-line { animation: draw-line 2s ease-in-out forwards; }
                .animate-draw-line-delayed { animation: draw-line-delayed 2s ease-in-out 0.5s forwards; }
                .animate-draw-line-slow { animation: draw-line-slow 2s ease-in-out 1s forwards; }
                .animate-count-up { animation: count-up 1s ease-out forwards; }
                .animate-count-up-delayed { animation: count-up 1s ease-out 0.3s forwards; }
                .animate-count-up-slow { animation: count-up 1s ease-out 0.6s forwards; }
            `
        }} />
    </section>

    {/* Community Section */}
    <section id="community" className="py-16 md:py-20 px-4 md:px-6 bg-white dark:bg-gray-900 w-full transition-colors duration-300">
        <div className="container mx-auto max-w-7xl">
            <div className="flex flex-col lg:flex-row items-start gap-8 md:gap-12">
                <div className="lg:w-1/2 flex flex-col h-full">
                    <h2 className="text-3xl md:text-4xl font-medium mb-6 text-gray-900 dark:text-white transition-colors duration-300">Join 150+ <span className="brand-text">Successful Traders</span></h2>
                    <p className="text-base md:text-lg text-[#19235d] dark:text-gray-300 mb-8 transition-colors duration-300">
                        When you purchase the Hextech Algo Trading System, you&apos;re not just getting software - you&apos;re joining an established community of 150+ successful forex traders with a proven track record.
                    </p>
                    
                    <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 mb-8 flex-grow transition-colors duration-300">
                        <h3 className="text-xl font-medium mb-4 text-gray-900 dark:text-white transition-colors duration-300">What You Get:</h3>
                        <ul className="space-y-4">
                            <li className="flex items-start">
                                <div className="flex-shrink-0 h-6 w-6 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center mt-1 transition-colors duration-300">
                                    <i className="fas fa-users text-green-600 dark:text-green-400 text-sm transition-colors duration-300"></i>
                                </div>
                                <p className="ml-3 text-[#19235d] dark:text-gray-300 transition-colors duration-300"><strong>Private Community</strong> – Direct access to experienced traders</p>
                            </li>
                            <li className="flex items-start">
                                <div className="flex-shrink-0 h-6 w-6 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center mt-1 transition-colors duration-300">
                                    <i className="fas fa-calendar-alt text-green-600 dark:text-green-400 text-sm transition-colors duration-300"></i>
                                </div>
                                <p className="ml-3 text-[#19235d] dark:text-gray-300 transition-colors duration-300"><strong>Monthly Live Webinars</strong> – Learn advanced strategies</p>
                            </li>
                            <li className="flex items-start">
                                <div className="flex-shrink-0 h-6 w-6 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center mt-1 transition-colors duration-300">
                                    <i className="fas fa-file-alt text-green-600 dark:text-green-400 text-sm transition-colors duration-300"></i>
                                </div>
                                <p className="ml-3 text-[#19235d] dark:text-gray-300 transition-colors duration-300"><strong>Market Analysis Reports</strong> – Weekly insights on major pairs</p>
                            </li>
                            <li className="flex items-start">
                                <div className="flex-shrink-0 h-6 w-6 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center mt-1 transition-colors duration-300">
                                    <i className="fas fa-laptop text-green-600 dark:text-green-400 text-sm transition-colors duration-300"></i>
                                </div>
                                <p className="ml-3 text-[#19235d] dark:text-gray-300 transition-colors duration-300"><strong>System Updates</strong> – Get all future upgrades</p>
                      </li>
                  </ul>
                    </div>
                    
                    <div className="mt-auto flex space-x-4">
                        <a href="https://t.me/+NgzWiBMfEj02YTM1" className="w-full sm:w-auto bg-green-500 dark:bg-green-600 text-white px-6 py-3 rounded-full flex items-center justify-center hover:bg-green-600 dark:hover:bg-green-700 transition duration-300">
                            Join the Community <i className="fas fa-arrow-right ml-2"></i>
                        </a>
                    </div>
                </div>
                
                {/* Placeholder for community image/video, if applicable */}
                <div className="lg:w-1/2 flex justify-center items-center h-full">
                    <div className="flex justify-center items-center w-full">
                        <dotlottie-player
                        src="https://lottie.host/32354f13-c19a-42fb-9075-78dc0dd14042/4EppzcR81P.lottie"
                        background="transparent"
                        speed="1"
                        style={{width: "500px", height: "500px"}}
                        loop
                        autoplay
                      ></dotlottie-player>
                                </div>
                </div>
            </div>
        </div>
    </section>

    
    </div>
    </section>
</>
  );
}
